server:
  port: 8080

yapily:
  base-url: https://api.yapily.com
  app-id: 60adff42-a0af-4654-aeaa-fa1fdc055ee7
  secret: shl1Ul7jegu4J5mBpdOhy4bixJ8mj0wO

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"             # expose all actuator endpoints
  endpoint:
    health:
      show-details: always
